const Data = [
  {
    id: 1,
    category: "education",
    icon: "icon-graduation",
    year: "2017 - 2019",
    title: "High School - Brazil",
    desc: "Colégio Santa Maria Minas, Belo Horizonte, MG",
  },
  {
    id: 2,
    category: "education",
    icon: "icon-graduation",
    year: "2019 - 2020",
    title: "Exchange Program - High School - Canada",
    desc: "Glebe Collegiate Institute, Ottawa, ON",
  },
  {
    id: 3,
    category: "education",
    icon: "icon-graduation",
    year: "2021 - present",
    title: "Computer Science Graduation",
    desc: "PUC Minas, Belo Horizonte, MG, Brazil",
  },
  {
    id: 4,
    category: "education",
    icon: "icon-graduation",
    year: "2025 - present",
    title: "Informatic Engineering Graduation",
    desc: "Instituto Politecnico da Guarda, Guarda, Portugal",
  },
  {
    id: 5,
    category: "experience",
    icon: "icon-briefcase",
    year: "2022 - 2023",
    title: "Monitoring",
    desc: "Helping students in subjects such as Algorithms and Data Structures and Intelligent Systems",
  },
  {
    id: 6,
    category: "experience",
    icon: "icon-briefcase",
    year: "2023 - 2024",
    title: "Andritz Internship",
    desc: "Development of new features and bug solutions",
  },
  {
    id: 7,
    category: "experience",
    icon: "icon-briefcase",
    year: "2024 - 2025",
    title: "DTI Internship",
    desc: "Development of new features and bug solutions",
  },
];

export default Data;
